graph LR
	A[Learning Paths] --> B(Coursera)
	B --> C(Preparing for Google Cloud Certification: Cloud Architect Specialization)
	C --> D(Architecting with Google Compute Engine Specialization)
	D --> E(Google Cloud Fundamentals: Core Infrastructure)
	D --> F(Essential Google Cloud Infrastructure: Foundation)
	D --> G(Essential Google Cloud Infrastructure: Core Services)
	D --> H(Elastic Google Cloud Infrastructure: Scaling and Automation)
	D --> I(Reliable Google Cloud Infrastructure: Design and Process)
	C --> J(Architecting with Google Kubernetes Engine: Foundations)
	C --> K(Preparing for the Google Cloud Professional Architecte Exam)
	E --> E1(Lab: Getting Started with Cloud Marketplace)
	E --> E2(Lab: Getting Started with Compute Engine)
	E --> E3(Lab: Getting Started with Cloud Storage and Cloud SQL)
	E --> E4(Lab: Getting Started with GKE)
	E --> E5(Lab: Getting Started with App Engine)
	E --> E6(Lab: Getting Started with Deployment Manager and Cloud Monitoring)
	E --> E7(Lab: Getting Started with BigQuery)
