flowchart TB
	classDef anode fill:#00ff00,stroke:#333,stroke-width:4px,height:50px,width:600px;

	A(Learning Paths) --> B(Coursera)
	B --> C(Preparing for Google Cloud Certification: Cloud Architect Specialization)
	C --> D(Architecting with Google Compute Engine Specialization)
	D --> E(Google Cloud Fundamentals: Core Infrastructure)
	D --> F(Essential Google Cloud Infrastructure: Foundation)
	D --> G(Essential Google Cloud Infrastructure: Core Services)
	D --> H(Elastic Google Cloud Infrastructure: Scaling and Automation)
	D --> I(Reliable Google Cloud Infrastructure: Design and Process)
	C --> J(Architecting with Google Kubernetes Engine: Foundations)
	C --> K(Preparing for the Google Cloud Professional Architect Exam)
	A --> L(QwikLabs)

	subgraph f-labs
	        direction TB
		F1(Lab: Getting Started with Cloud Marketplace)
		F2(Lab: Getting Started with Compute Engine)
		F3(Lab: Getting Started with Cloud Storage and Cloud SQL)
	        F1 --> F2 --> F3
	end
	F --> f-labs

	subgraph e-labs
	        direction TB
		E1(Lab: Getting Started with Cloud Marketplace)
		E2(Lab: Getting Started with Compute Engine)
		E3(Lab: Getting Started with Cloud Storage and Cloud SQL)
		E4(Lab: Getting Started with GKE)
		E5(Lab: Getting Started with App Engine)
		E6(Lab: Getting Started with Deployment Manager and Cloud Monitoring)
		E7(Lab: Getting Started with BigQuery)
	        E1 --> E2 --> E3 --> E4 --> E5 --> E6 --> E7
	end
	E --> e-labs

	subgraph m-labs
	        direction TB
		M1(Lab: A Tour of Google Cloud Hands-on Labs)
		M2(Lab: Creating a Virtual Machine)
		M3(Lab: Compute Engine: Qwik Start - Windows)
		M4(Lab: Getting Started with Cloud Shell and gcloud)
		M5(Lab: Kubernetes Engine: Qwik Start)
		M6(Lab: Set Up Network and HTTP Load Balancers)
		M1 --> M2 --> M3 --> M4 --> M5 --> M6
	end
	L --> M(Quest: Google Cloud Essentials)
	M --> N --> O --> m-labs

	subgraph s-labs
	        direction TB
		S1(Lab: Configuring Networks via gcloud)
		S2(Lab: Configuring IAM Permissions wth gcloud)
		S3(Lab: Using gsutil to Perform Operations on Buckets and Objects)
		S4(Lab: BigQuery: Qwik Start - Command Line)
		S1 --> S2 --> S3 --> S4
	end
	L --> P(Quest: Using the Cloud SDK Command Line)
	P --> s-labs
	s-labs --> M4
